/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;
import javax.swing.JOptionPane;
import modelo.Libro;

/**
 *
 * @author usuario
 */
public class PanelDatosLibro extends javax.swing.JPanel {

    /**
     * Creates new form PanelDatosLibro
     */
    public PanelDatosLibro() {
        initComponents();
    }

    public Libro getLibro()
    {
      Libro libro= new Libro(jtISBN.getText(), jtTítulo.getText(), jtAutor.getText()); 
      return libro;
    }
    
    public boolean verificarDatos()
    { 
        boolean variable= false;
        if(!jtISBN.getText().equals("") && !jtTítulo.getText().equals("") && !jtAutor.getText().equals(""))
        {
            
            variable=true;
            
        }
        else
        {
            JOptionPane.showMessageDialog(this, "Por favor llene los espacios");
        }
        return variable;
     }      
   
    
    public String getISBN()
    {
        return jtISBN.getText(); 
    }
    
     public String getTitulo()
    {
        return jtTítulo.getText(); 
    }
     
   public String getAutor()
    {
        return jlAutor.getText(); 
    }
    
    
    
    public void limpiar()
    {
      jtISBN.setText(" ");
      jtTítulo.setText(" ");
      jtAutor.setText(" ");
      
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlISBN = new javax.swing.JLabel();
        jtISBN = new javax.swing.JTextField();
        jlTítulo = new javax.swing.JLabel();
        jtTítulo = new javax.swing.JTextField();
        jlAutor = new javax.swing.JLabel();
        jtAutor = new javax.swing.JTextField();

        setBackground(new java.awt.Color(127, 195, 184));

        jlISBN.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jlISBN.setText("ISBN");

        jlTítulo.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jlTítulo.setText("Título");

        jlAutor.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jlAutor.setText("Autor");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jlISBN)
                        .addGap(27, 27, 27)
                        .addComponent(jtISBN, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jlAutor)
                                .addGap(18, 18, 18)
                                .addComponent(jtAutor))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jlTítulo)
                                .addGap(18, 18, 18)
                                .addComponent(jtTítulo, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 26, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlISBN)
                    .addComponent(jtISBN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlTítulo)
                    .addComponent(jtTítulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jlAutor)
                    .addComponent(jtAutor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(23, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jlAutor;
    private javax.swing.JLabel jlISBN;
    private javax.swing.JLabel jlTítulo;
    private javax.swing.JTextField jtAutor;
    private javax.swing.JTextField jtISBN;
    private javax.swing.JTextField jtTítulo;
    // End of variables declaration//GEN-END:variables
}
